### PR TITLE
[New Branch?] Backport to 1.14.4

### PR DESCRIPTION
**Pull request by halotroop2288**
I want to use Cotton Config and Cotton Logger in the 1.14.4 version of a mod, but it crashes with a Jankson error. So, clearly, the best way to fix it is to backport the new version of Jankson to the old version of Minecraft.
Well, it works, anyway. It fixed my issue.
Screenshot

### CODE REVIEW

**Comment by falkreon** [comment]
Hmm. I'm watching this carefully. I *think* this is okay, just don't backport jankson 1.2.0 (`+j1.2.0`) all the way back to versions that don't have it (1.1.x -> 1.2.x contains breaking changes)

**Comment by Bluberry-Kat** [comment]
There doesn't appear to be any obvious problems with this. Are we good to merge?

**Comment by LemmaEOF** [comment]
The best option would to change your cotton backport's use of `blue.endless.jankson.api.SyntaxError` to `blue.endless.jankson.impl.SyntaxError`, I think.

**Comment by LemmaEOF** [comment]
but yeah I think this is safe to merge, lemme give ya perms

**Comment by falkreon** [comment]
After reviewing the Jankson-Fabric history, I'm afraid this isn't safe to merge: Existing Minecraft 1.14 mods use 1.1.x Jankson, which will cause API incompatibilities if this fork is introduced.

The only way to get 1.2.x or bleeding Jankson into Minecraft 1.14, is to use shadow+remap to pull in Jankson from mavenCentral into a new namespace, and use it directly.

**Comment by halotroop2288** [comment]
@falkreon
Can you please be more specific about "shadow+remap"?
What does that mean?
Do I have to change my mod's build.gradle, or start over on my PR and do something to Jankson-Fabric?
And what exactly is it that I have to change?

**Pull request closed without merging**
